server:
  port: 8081

spring:
  redis:
    database: 0 #redis数据库索引,默认为0,如果选择1,则数据存放在select 1中
    host: 10.10.4.163 #redis服务器IP地址,默认为localhost
    port: 6379 #redis进程使用端口号,默认为6379
    password: #密码默认为空
    jedis:
      pool:
        max-active: 600 #连接池最大连接数
        max-wait: 1000ms #连接池最大阻塞等待时间 -1表示没有限制,单位毫秒
        max-idle: 300 #连接池最大空闲连接数
        min-idle: 0 #连接池最小空闲连接数
    timeout: 10000ms #访问超时时间
    ssl: false #不开启ssl认证
    url:




